version: '3.3'

volumes:
  pg_data:
  static:
  users_media:

services:
  db:
    image: postgres:13
    env_file: .env
    volumes:
      - pg_data:/var/lib/postgresql/data
  backend:
    image: tancher5/foodgram_backend
    env_file: .env
    volumes:
      - static:/backend_static
      - users_media:/app/media/
    depends_on:
      - db
  frontend:
    image: tancher5/foodgram_frontend
    command: cp -r /app/build/. /static/
    volumes:
      - static:/static
  gateway:
    image: tancher5/foodgram_gateway
    ports:
      - 7000:80
    volumes:
      - static:/static
      - users_media:/media
    depends_on:
      - backend
