TAG_NAME_MAX_LENGHT = 32
TAG_SLUG_MAX_LENGHT = 32
INGREDIENT_NAME_MAX_LENGHT = 128
INGREDIENT_MEASUREMENT_UNIT_MAX_LENGHT = 64
RECIPE_NAME_MAX_LENGHT = 256
TEXT_MAX_LENGHT_FOR_ADMIN_ZONE = 20
CODE_FOR_RECIPE_SHORT_LINK_MAX_LENGTH = 3
