# Generated by Django 3.2.16 on 2024-07-18 13:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0002_recipeshortlink'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='recipeshortlink',
            name='short_link',
        ),
        migrations.AddField(
            model_name='recipeshortlink',
            name='short_code',
            field=models.CharField(default=123, max_length=6, unique=True),
            preserve_default=False,
        ),
    ]
