# Generated by Django 3.2.16 on 2024-07-29 10:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0003_auto_20240727_1619'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='short_code',
            field=models.CharField(blank=True, default='', max_length=3, unique=True),
            preserve_default=False,
        ),
    ]
